### ISSUE TITLE
Invalid condition

### ISSUE THREAD

**Issue by ghost** [recp/xml#4]
https://github.com/recp/xml/blob/43e7c9d71c6d4610aea7fbfb3ddae54097db9813/include/xml/impl/impl_common.h#L67
I think you missed the "!" in (iter = current->next)

**Comment by recp** [comment]
Hi @tekanaori,

Wow thanks for the catch! 

The https://github.com/recp/xml/commit/c53989495b050cc9d45f4fd561e9e77ab7be0b94 commit should fix the issue
